[package]
name = "datadog"
version = "0.1.0"
authors = ["Shella Stephens <shella@iqlusion.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
